add install

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -4,6 +4,57 @@
 apt-get install automake libtool git ffmpeg
 git clone https://github.com/devowlio/node-fdkaac.git
 cd node-fdkaac
-ls
-chmod +x install.sh
-./install.sh
+
+commandExists() {
+    type "$1" &> /dev/null;
+}
+
+if ! commandExists automake ; then
+    echo "Command not found: automake"
+    exit 1
+fi
+
+if ! commandExists libtool ; then
+    if ! commandExists libtoolize ; then
+        echo "Command not found: libtool"
+        exit 1
+    fi
+
+    ln -s /usr/bin/libtoolize /usr/bin/libtool
+fi
+
+if ! commandExists git ; then
+    echo "Command not found: git"
+    exit 1
+fi
+
+# Create lib folders
+if [ -d "bin" ]; then
+    rm -rf bin
+fi
+
+mkdir bin
+cd bin
+
+# Install libfdk-aac (see https://github.com/mstorsjo/fdk-aac)
+printf "Install fdk-aac (also called libfdk-aac)\n\n"
+
+git clone https://github.com/mstorsjo/fdk-aac libfdk-aac
+cd libfdk-aac
+./autogen.sh
+./configure --enable-shared --enable-static
+make
+make install
+
+cd ..
+
+# Install fdkaac (see https://github.com/nu774/fdkaac)
+printf "Install fdkaac\n"
+
+git clone https://github.com/nu774/fdkaac
+cd fdkaac
+autoreconf -i
+./configure
+make
+make install
+ldconfig
